Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartTicket.Models;
using SmartTicket.Services;
using System.Security.Claims;

namespace SmartTicket.Controllers
{
    [Authorize]
    public class CartController : Controller
    {

        public CartController(SmartTicketContext myDb, UserManager<IdentityUser> userManager, IEmailService emailService)
        {
            _myDB = myDb;
            _userManager = userManager;
            _emailService = emailService;
        }

        private readonly SmartTicketContext _myDB;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailService _emailService;

        [HttpGet]
        public IActionResult Index()
        {
            string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

            var userCart = _myDB.carts.FirstOrDefault(x => x.UserId.Contains(id));

            if (userCart == null)
            {
                return BadRequest(new { error = $"Invalid user id {id}" });
            }

            var userCartDetails = _myDB.cartDetails.Include(y => y.Movie).Include(m => m.cart).Where(x => x.cartId == userCart.Id).ToList();
            
            /*
            if (userCartDetails == null || userCartDetails.Count == 0)
            {
                return Ok(new { msg = $"Cart id {userCart.Id} is empty" });
            }
            */
            return View(userCartDetails);
        }

        [HttpPost]
        public IActionResult Add(int Id)
        {
            if (Id != 0)
            {
                string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

                var userCart = _myDB.carts.FirstOrDefault(x => x.UserId.Contains(id));

                if (userCart == null)
                {
                    return NotFound(new { error = $"Invalid user id {id}" });
                }

                var userMovie = _myDB.Movies.FirstOrDefault(x => x.Id == Id);

                if (userCart == null)
                {
                    return NotFound(new { error = $"Invalid user id {id}" });
                }

                _myDB.cartDetails.Add(new cartDetails { cartId=userCart.Id, movieId= Id });
                _myDB.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", "Home");

        }


        [HttpGet]
        [HttpDelete]
        public IActionResult Clear()
        {
			string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

			var userCart = _myDB.carts.FirstOrDefault(x => x.UserId.Contains(id));

			if (userCart == null)
			{
				return NotFound(new { error = $"Invalid user id {id}" });
			}

			var userCartDetails = _myDB.cartDetails.Where(x => x.cartId == userCart.Id).ToList();

            foreach(var cartDetails in userCartDetails)
            {
                _myDB.cartDetails.Remove(cartDetails);
            }

            _myDB.SaveChanges();

			return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult decrease(int cartDetailsId) 
        {
			string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

			var userCart = _myDB.carts.FirstOrDefault(x => x.UserId.Contains(id));

			if (userCart == null)
			{
				return NotFound(new { error = $"Invalid user id {id}" });
			}

            var cartDetailsEntity = _myDB.cartDetails.FirstOrDefault(x=>x.Id == cartDetailsId);

            if (cartDetailsEntity == null) 
            {
				return RedirectToAction("Index");
			}

            _myDB.cartDetails.Remove(cartDetailsEntity);
            _myDB.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult increase(int movieId)
		{
			string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

			var userCart = _myDB.carts.FirstOrDefault(x => x.UserId.Contains(id));

			if (userCart == null)
			{
				return NotFound(new { error = $"Invalid user id {id}" });
			}

            _myDB.cartDetails.Add(new cartDetails { cartId=userCart.Id, movieId=movieId});
            _myDB.SaveChanges();

			return RedirectToAction("Index");
		}

        [HttpGet]
        public async Task<IActionResult> checkout()
        {
			string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
			string email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value;

			Order newOrder = new Order() { userId= id };
            _myDB.Orders.Add(newOrder);
			_myDB.SaveChanges();

			var cartItems = _myDB.cartDetails.Include(x=>x.Movie).ToList();

            if (cartItems.Count == 0) 
            {
			    return RedirectToAction("Index", "Home");
			}

			foreach (var cartItem in cartItems)
            {
                _myDB.OrderDetails.Add(new OrderDetails {orderId=newOrder.Id, movieId=cartItem.movieId });
            }

            _myDB.SaveChanges();

            string msgBody = "";

            foreach (var cartItem in cartItems)
            {
                msgBody += $"Movie: {cartItem.Movie.Name}, Price: {cartItem.Movie.Price}, StartData: {cartItem.Movie.StartDate}, EndDate: {cartItem.Movie.EndDate}";
                await _emailService.sendMailAsync(email, "Movie Ticket", msgBody);
                msgBody = "";
            }

            foreach (var cartItem in cartItems)
			{
			    _myDB.cartDetails.Remove(cartItem);
            }

			_myDB.SaveChanges();

			return View("checkout", email);
        }

	}
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartTicket.Models;
using SmartTicket.Services;

namespace SmartTicket.Controllers
{

    public class MoviesController : Controller
    {

        public MoviesController(IService<Movie> movieService, IService<Category> categoryService, IService<Cinema> cinemaService, IService<MovieActor> movieActorService) 
        {
            _movieService = movieService;
            _categoryService = categoryService;
            _cinemaService = cinemaService;
            _movieActorService = movieActorService;
        }

        private readonly IService<Movie> _movieService;
        private readonly IService<Category> _categoryService;
        private readonly IService<Cinema> _cinemaService;
        private readonly IService<MovieActor> _movieActorService;

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var tempMovies = await _movieService.GetAll();

            return View(tempMovies);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add()
        {
			ViewBag.CatId = new SelectList(await _categoryService.GetAll(), "Id", "Name");
			ViewBag.cinemaId = new SelectList(await _cinemaService.GetAll(), "Id", "Name");

			return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add(Movie newMovie)
		{
            if (ModelState.IsValid)
            {
                await _movieService.Create(newMovie);
                return RedirectToAction("Index", "Home");
			}

			ViewBag.CatId = new SelectList(await _categoryService.GetAll(), "Id", "Name");
			ViewBag.cinemaId = new SelectList(await _cinemaService.GetAll(), "Id", "Name");

			return View(newMovie);
		}

        [HttpGet]
        public async Task<IActionResult> Details( int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var movie = await _movieService.getById(id);

            if (movie == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var tempActors = await _movieActorService.getMovieACtorForMovie(id);

            if (tempActors != null && tempActors.Count != 0)
            {
                ViewBag.actos = tempActors;
            }

            movie.Views += 1;

            await _movieService.commit();

            return View(movie);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var movie = await _movieService.getById(id);

            if (movie == null)
            {
                return RedirectToAction("Index", "Home");
            }

            await _movieService.Delete(id);

            TempData["delMsg"] = $"Movie {movie.Name} has been deleted succfully";

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {

            if (id == 0)
            {
                return NotFound("Invalid movie id");
            }

            var movieEntity = await _movieService.getById(id);

            if (movieEntity == null)
            {
                return NotFound("Invalid movie id");
            }
			ViewBag.CatId = new SelectList(await _categoryService.GetAll(), "Id", "Name");
			ViewBag.cinemaId = new SelectList(await _cinemaService.GetAll(), "Id", "Name");

			return View(movieEntity);
        }

		[HttpPost]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Edit(int id, Movie newMovie)
		{
			if (ModelState.IsValid)
			{
				await _movieService.Update(id, newMovie);
				return RedirectToAction("Index", "Home");
			}

			ViewBag.CatId = new SelectList(await _categoryService.GetAll(), "Id", "Name");
			ViewBag.cinemaId = new SelectList(await _cinemaService.GetAll(), "Id", "Name");

			return View(newMovie);
		}


	}
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartTicket.Models;
using System.Security.Claims;

namespace SmartTicket.Controllers
{
	[Authorize]
	public class OrderController : Controller
	{

        public OrderController(SmartTicketContext myDb)
        {
            _myDb = myDb;
        }

		private readonly SmartTicketContext _myDb;

        public IActionResult Index()
		{
			string id = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

			var orders = _myDb.Orders.Where(x=>x.userId == id).ToList();

			return View("Index", orders);
		}

		[HttpGet]
		public IActionResult Details(int id) 
		{
			string UserId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

			var userOrder = _myDb.Orders.FirstOrDefault(x=>x.Id == id && x.userId == UserId);

			if (userOrder == null) 
			{ 
				return RedirectToAction("Index", "Home");
			}

			List<OrderDetails> orders = _myDb.OrderDetails.Include(x=>x.Movie).Where(x=>x.orderId== userOrder.Id).ToList();

			return View("Details", orders);

		}

	}
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SmartTicket.DTO;

namespace SmartTicket.Controllers
{
    [Authorize(Roles = "Admin")]

    public class RoleController : Controller
	{


		public RoleController(RoleManager<IdentityRole> roleManager) 
		{
			_roleManager = roleManager;
		}

		private readonly RoleManager<IdentityRole> _roleManager;

		public async Task<IActionResult> Index()
		{
			return View();
		}


		[HttpGet]
		public async Task<IActionResult> Add() 
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Add(RoleDTO newRole)
		{
			if(ModelState.IsValid)
			{

				var isRoleExists = await _roleManager.RoleExistsAsync(newRole.Name);

                if (!isRoleExists)
				{
                    IdentityRole tempRole = new IdentityRole(newRole.Name);

                    var res = await _roleManager.CreateAsync(tempRole);

                    if (res.Succeeded)
                    {
                        return View();
                    }

                    string errorDetails = "";

                    foreach (var error in res.Errors)
                    {
                        errorDetails += error.Description + ", ";
                    }

                    return NotFound(errorDetails);

                }
            }



			return View();

		}

	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartTicket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartTicket.styles.css" asp-append-version="true" />
    <link rel="icon" href="https://cdn-icons-png.freepik.com/512/6030/6030249.png" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 px-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SmartTicket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!-- Example single danger button -->
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-text-left"></i>
                                Dashboard
                            </button>
                            <ul class="dropdown-menu">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                    </li>
                                }

                                <li class="nav-item">
                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Actor" asp-action="Index">Actor</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="movieActor" asp-action="Index">movieActor</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link dropdown-item text-dark" asp-area="" asp-controller="Role" asp-action="Add">Role</a>
                                </li>
                            </ul>
                        </div>


                    </ul>
                </div>
            </div>


            <div class="d-flex ">
                @if (!User.Identity.IsAuthenticated)
                {
                    <div>
                        <a asp-area="" asp-controller="Account" asp-action="Login">
                            <button class="btn btn-outline-secondary">Login</button>
                        </a>
                    </div>

                    <div>
                        <a class="mx-3" asp-area="" asp-controller="Account" asp-action="Regester">
                            <button class="btn btn-outline-primary">Regester</button>
                        </a>
                    </div>
                }


                @if (User.Identity.IsAuthenticated)
                {
                    <a  class="mx-3" asp-area="" asp-controller="Account" asp-action="SignOut">
                        <button class="btn btn-outline-danger">SignOut</button>
                    </a>
                }


                
            </div>

            <div>
                <form method="get" asp-controller="Search" asp-action="Index">
                    <div class="d-flex gap-3">
                        <input name="name" id="name" placeholder="Search for movies ..." class="form-control" />
                        <button class="btn btn-outline-secondary">Search</button>

                    </div>


                </form>


            </div>
        </nav>
    </header>
    <div class="container my-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SmartTicket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>