Models/MovieActor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartTicket.Models
{
	public class MovieActor
	{
		[Key]
        public int Id { get; set; }

        [ForeignKey("Movie")]
        public int MovieId { get; set; }

        public Movie? Movie { get; set; }

        [ForeignKey("Actor")]
        public int? ActorId { get; set; }

        public Actor? Actor { get; set; }


    }
}

Controllers/movieActorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartTicket.Models;
using SmartTicket.Services;

namespace SmartTicket.Controllers
{
    [Authorize(Roles = "Admin")]

    public class movieActorController : Controller
    {


        public movieActorController(IService<MovieActor> movieActorService, IService<Movie> movieService, IService<Actor> actorService)
        {
			_movieActorService = movieActorService;
			_movieService = movieService;
			_actorService = actorService;
        }

        private readonly IService<MovieActor> _movieActorService;
        private readonly IService<Movie> _movieService;
        private readonly IService<Actor> _actorService;

        public async Task<IActionResult> Index()
        {
            var movieActor = await _movieActorService.GetAll();
            return View(movieActor);
        }

		[HttpGet]
		public async Task<IActionResult> Add()
		{
			ViewBag.movieId = new SelectList(await _movieService.GetAll(), "Id", "Name");
			ViewBag.actorId = new SelectList(await _actorService.GetAll(), "Id", "FirstName");

			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Add(MovieActor newMovieActor)
		{
			if (ModelState.IsValid)
			{
				await _movieActorService.Create(newMovieActor);
				return RedirectToAction("Index");
			}
			ViewBag.movieId = new SelectList(await _movieService.GetAll(), "Id", "Name");
			ViewBag.actorId = new SelectList(await _actorService.GetAll(), "Id", "FirstName");

			return View(newMovieActor);
		}

		[HttpGet]
		public async Task<IActionResult> Delete(int id)
		{
			var tempMovieActor = _movieActorService.getById(id);
			if (tempMovieActor == null) 
			{
				return NotFound($"Invalid MovieActor Id {id}");
			}

			await _movieActorService.Delete(id);

			return RedirectToAction("Index");

		}


    }
}

Views/movieActor/Add.cshtml
@model MovieActor


<div class="my-5">
	<form method="post" asp-controller="movieActor" asp-action="Add">
		<h2 class="my-4">New MovieActor</h2>
		

		<div class="my-4">
			<label class="mb-1">Movie</label>
			<select class="form-control" asp-for="MovieId" asp-items="ViewBag.movieId">
			</select>
		</div>

		<div class="my-4">
			<label class="mb-1">Actor</label>
			<select class="form-control" asp-for="ActorId" asp-items="ViewBag.actorId">
			</select>
		</div>

		<div class="my-4">
			<button class="btn btn-primary" type="submit">Save</button>
			<a class="btn btn-info mx-2" asp-controller="movieActor" asp-action="Index">Back</a>
		</div>

	</form>
</div>


@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

Views/movieActor/Index.cshtml
<! -- strong type generac -->
@model ICollection<MovieActor>


@if (TempData["msg"] != null)
{
	<h3 class="text-info">@TempData["msg"]</h3>
}

@if (TempData["successMsg"] != null)
{
	<h3 class="text-success">@TempData["successMsg"]</h3>
}

<h2 class="my-5">My MovieActor</h2>

<div>
	<table class="table table-bordered table-hover">
		<thead>
			<tr>
				<td>Id</td>
				<td>movie</td>
				<td>actor</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
			@foreach (var elm in Model)
			{
				<tr>
					<td class="p-2">@elm.Id</td>
					<td class="p-2">
						@elm.Movie.Name
					</td>
					<td class="p-2">
						@elm.Actor.FirstName @elm.Actor.LastName
					</td>
					<td class="px-3 py-2">
						<div class="d-flex align-items-center gap-3">
							<div class="w-100">
								<!-- <a asp-controller="Courses" asp-action="Edit" asp-route-id="elm.Id" class="btn w-100  btn-info">Edit</a> -->
								<a asp-controller="movieActor" asp-action="Edit" asp-route-Id="@elm.Id" class="btn w-100  btn-info">Edit</a>

							</div>
							<div class="w-100">
								<a asp-controller="movieActor" asp-action="Delete" asp-route-Id="@elm.Id" class="btn w-100  btn-danger">Delete</a>
							</div>
						</div>
					</td>
				</tr>
			}

		</tbody>

	</table>
	<div class="my-4">
		<a asp-controller="movieActor" asp-action="Add" class="btn btn-primary">New MovieActor</a>
	</div>
</div>